UNIVERSITY_CONFIG = {
    'Harvard': {
        'full_name': 'Harvard University',
        'logo_url': 'https://i.imgur.com/YH3we7s.png',
        'primary_color': '#A51C30',
        'subdomain': 'harvard',
        'contact_email': 'admissions@harvard.edu',
        'contact_phone': '(617) 495-1000',
    },
    'Yale': {
        'full_name': 'Yale University',
        'logo_url': 'https://i.imgur.com/hHCe2tj.png',
        'primary_color': '#0F4C81',
        'subdomain': 'yale',
        'contact_email': 'admissions@yale.edu',
        'contact_phone': '(203) 432-9300',
    },
    'Stanford': {
        'full_name': 'Stanford University',
        'logo_url': 'https://i.imgur.com/MtkBdYW.png',
        'primary_color': '#8C1515',
        'subdomain': 'stanford',
        'contact_email': 'admissions@stanford.edu',
        'contact_phone': '(650) 723-2091',
    },
    'Dartmouth': {
        'full_name': 'Dartmouth College',
        'logo_url': 'https://i.imgur.com/example-dartmouth.png',
        'primary_color': '#006633',
        'subdomain': 'dartmouth',
        'contact_email': 'admissions@dartmouth.edu',
        'contact_phone': '(603) 646-2875',
    },
    'Duke': {
        'full_name': 'Duke University',
        'logo_url': 'https://i.imgur.com/example-duke.png',
        'primary_color': '#00539B',
        'subdomain': 'duke',
        'contact_email': 'admissions@duke.edu',
        'contact_phone': '(919) 684-3214',
    },
    'Princeton': {
        'full_name': 'Princeton University',
        'logo_url': 'https://i.imgur.com/example-princeton.png',
        'primary_color': '#EE7F2D',
        'subdomain': 'princeton',
        'contact_email': 'admissions@princeton.edu',
        'contact_phone': '(609) 258-3000',
    },
    'Uchicago': {
        'full_name': 'University of Chicago',
        'logo_url': 'https://i.imgur.com/example-uchicago.png',
        'primary_color': '#800000',
        'subdomain': 'uchicago',
        'contact_email': 'admissions@uchicago.edu',
        'contact_phone': '(773) 702-8650',
    },
    'Nyuad': {
        'full_name': 'New York University Abu Dhabi',
        'logo_url': 'https://i.imgur.com/example-nyuad.png',
        'primary_color': '#57068C',
        'subdomain': 'nyuad',
        'contact_email': 'admissions@nyuad.nyu.edu',
        'contact_phone': '+971 2 619 4444',
    },
    # Ivy League additions
    'Columbia': {
        'full_name': 'Columbia University',
        'logo_url': 'https://i.imgur.com/example-columbia.png',
        'primary_color': '#ABB470',
        'subdomain': 'columbia',
        'contact_email': 'ugrad-admissions@columbia.edu',
        'contact_phone': '(212) 854-2522',
    },
    'Brown': {
        'full_name': 'Brown University',
        'logo_url': 'https://i.imgur.com/example-brown.png',
        'primary_color': '#4E3629',
        'subdomain': 'brown',
        'contact_email': 'admission_undergraduate@brown.edu',
        'contact_phone': '(401) 863-2378',
    },
    'Cornell': {
        'full_name': 'Cornell University',
        'logo_url': 'https://i.imgur.com/example-cornell.png',
        'primary_color': '#B31B1B',
        'subdomain': 'cornell',
        'contact_email': 'admissions@cornell.edu',
        'contact_phone': '(607) 255-5241',
    },
    'Upenn': {
        'full_name': 'University of Pennsylvania',
        'logo_url': 'https://i.imgur.com/example-upenn.png',
        'primary_color': '#011F5B',
        'subdomain': 'upenn',
        'contact_email': 'info@admissions.upenn.edu',
        'contact_phone': '(215) 898-7507',
    },
    # Top-tier additions
    'MIT': {
        'full_name': 'Massachusetts Institute of Technology',
        'logo_url': 'https://i.imgur.com/example-mit.png',
        'primary_color': '#A31F34',
        'subdomain': 'mit',
        'contact_email': 'admissions@mit.edu',
        'contact_phone': '(617) 253-3400',
    },
    'Caltech': {
        'full_name': 'California Institute of Technology',
        'logo_url': 'https://i.imgur.com/example-caltech.png',
        'primary_color': '#F47F20',
        'subdomain': 'caltech',
        'contact_email': 'ugadmissions@caltech.edu',
        'contact_phone': '(626) 395-6811',
    },
    'Northwestern': {
        'full_name': 'Northwestern University',
        'logo_url': 'https://i.imgur.com/example-northwestern.png',
        'primary_color': '#4E2A84',
        'subdomain': 'northwestern',
        'contact_email': 'ug-admission@northwestern.edu',
        'contact_phone': '(847) 491-3741',
    },
    'Johnshopkins': {
        'full_name': 'Johns Hopkins University',
        'logo_url': 'https://i.imgur.com/example-johnshopkins.png',
        'primary_color': '#002D56',
        'subdomain': 'johnshopkins',
        'contact_email': 'apply@jhu.edu',
        'contact_phone': '(410) 516-8171',
    },
    'Rice': {
        'full_name': 'Rice University',
        'logo_url': 'https://i.imgur.com/example-rice.png',
        'primary_color': '#003366',
        'subdomain': 'rice',
        'contact_email': 'admissions@rice.edu',
        'contact_phone': '(713) 348-0000',
    },
    'Vanderbilt': {
        'full_name': 'Vanderbilt University',
        'logo_url': 'https://i.imgur.com/example-vanderbilt.png',
        'primary_color': '#836634',
        'subdomain': 'vanderbilt',
        'contact_email': 'admissions@vanderbilt.edu',
        'contact_phone': '(615) 322-7311',
    },
    'NotreDame': {
        'full_name': 'University of Notre Dame',
        'logo_url': 'https://i.imgur.com/example-notredame.png',
        'primary_color': '#0C2340',
        'subdomain': 'notredame',
        'contact_email': 'admissions@nd.edu',
        'contact_phone': '(574) 631-7505',
    },
    'WashU': {
        'full_name': 'Washington University in St. Louis',
        'logo_url': 'https://i.imgur.com/example-washu.png',
        'primary_color': '#A51926',
        'subdomain': 'washu',
        'contact_email': 'admissions@wustl.edu',
        'contact_phone': '(314) 935-6000',
    },
    'Emory': {
        'full_name': 'Emory University',
        'logo_url': 'https://i.imgur.com/example-emory.png',
        'primary_color': '#B40404',
        'subdomain': 'emory',
        'contact_email': 'admissions@emory.edu',
        'contact_phone': '(404) 727-6030',
    },
    'Georgetown': {
        'full_name': 'Georgetown University',
        'logo_url': 'https://i.imgur.com/example-georgetown.png',
        'primary_color': '#13294B',
        'subdomain': 'georgetown',
        'contact_email': 'georgetown@georgetown.edu',
        'contact_phone': '(202) 687-3600',
    },
    'Berkeley': {
        'full_name': 'University of California, Berkeley',
        'logo_url': 'https://i.imgur.com/example-berkeley.png',
        'primary_color': '#003262',
        'subdomain': 'berkeley',
        'contact_email': 'ugaoffice@berkeley.edu',
        'contact_phone': '(510) 664-3010',
    },
    'UCLA': {
        'full_name': 'University of California, Los Angeles',
        'logo_url': 'https://i.imgur.com/example-ucla.png',
        'primary_color': '#2774AE',
        'subdomain': 'ucla',
        'contact_email': 'ugadm@admission.ucla.edu',
        'contact_phone': '(310) 825-3101',
    },
    'Michigan': {
        'full_name': 'University of Michigan',
        'logo_url': 'https://i.imgur.com/example-michigan.png',
        'primary_color': '#00274C',
        'subdomain': 'michigan',
        'contact_email': 'admissions.umich@umich.edu',
        'contact_phone': '(734) 764-7433',
    },
    'UNC': {
        'full_name': 'University of North Carolina at Chapel Hill',
        'logo_url': 'https://i.imgur.com/example-unc.png',
        'primary_color': '#56A0D3',
        'subdomain': 'unc',
        'contact_email': 'uncadmissions@unc.edu',
        'contact_phone': '(919) 962-2211',
    },
    'UVA': {
        'full_name': 'University of Virginia',
        'logo_url': 'https://i.imgur.com/example-uva.png',
        'primary_color': '#232D4B',
        'subdomain': 'uva',
        'contact_email': 'undergradadmission@virginia.edu',
        'contact_phone': '(434) 924-7184',
    },
    'GeorgiaTech': {
        'full_name': 'Georgia Institute of Technology',
        'logo_url': 'https://i.imgur.com/example-gatech.png',
        'primary_color': '#B3A369',
        'subdomain': 'gatech',
        'contact_email': 'admission@gatech.edu',
        'contact_phone': '(404) 894-4154',
    },
    'Carnegie': {
        'full_name': 'Carnegie Mellon University',
        'logo_url': 'https://i.imgur.com/example-cmu.png',
        'primary_color': '#C41230',
        'subdomain': 'carnegie',
        'contact_email': 'undergraduate-admissions@andrew.cmu.edu',
        'contact_phone': '(412) 268-2082',
    },
    'NYU': {
        'full_name': 'New York University',
        'logo_url': 'https://i.imgur.com/example-nyu.png',
        'primary_color': '#57068C',
        'subdomain': 'nyu',
        'contact_email': 'admissions@nyu.edu',
        'contact_phone': '(212) 998-4500',
    },
    'USC': {
        'full_name': 'University of Southern California',
        'logo_url': 'https://i.imgur.com/example-usc.png',
        'primary_color': '#990000',
        'subdomain': 'usc',
        'contact_email': 'admit@usc.edu',
        'contact_phone': '(213) 740-1111',
    },
    'Tufts': {
        'full_name': 'Tufts University',
        'logo_url': 'https://i.imgur.com/example-tufts.png',
        'primary_color': '#417DC1',
        'subdomain': 'tufts',
        'contact_email': 'admissions@tufts.edu',
        'contact_phone': '(617) 627-3170',
    },
    'WakeForest': {
        'full_name': 'Wake Forest University',
        'logo_url': 'https://i.imgur.com/example-wakeforest.png',
        'primary_color': '#9D2235',
        'subdomain': 'wakeforest',
        'contact_email': 'admissions@wfu.edu',
        'contact_phone': '(336) 758-4264',
    }
}
