# Generated by Django 4.2.9 on 2024-12-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_decision', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=100)),
                ('last_decision', models.CharField(max_length=50)),
                ('letters_generated', models.IntegerField(default=1)),
                ('first_generated_at', models.DateTimeField(auto_now_add=True)),
                ('last_generated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Letter Generation',
                'verbose_name_plural': 'Letter Generations',
            },
        ),
    ]
