# Generated by Django 4.2.9 on 2024-12-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_decision', '0002_lettergeneration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lettergeneration',
            name='last_decision',
        ),
        migrations.RemoveField(
            model_name='lettergeneration',
            name='university',
        ),
        migrations.CreateModel(
            name='UniversityDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=100)),
                ('decision_type', models.CharField(choices=[('Acceptance', 'Acceptance'), ('Rejection', 'Rejection')], max_length=20)),
                ('decision_count', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('university', 'decision_type')},
            },
        ),
    ]
