# Generated by Django 4.2.9 on 2025-11-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("college_decision", "0003_remove_lettergeneration_last_decision_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DecisionToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("full_name", models.CharField(max_length=255)),
                ("university", models.CharField(max_length=100)),
                ("decision", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("application_id", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("viewed", models.BooleanField(default=False)),
                ("viewed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
